version: '3.7'

services:
    db:
        container_name: postgres
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DATABASE=${POSTGRES_DATABASE}
        ports:
            - 5433:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - teastream-backend

    redis:
        container_name: redis
        image: redis:5.0
        restart: always
        ports:
            - 6379:6379
        command: redis-server --requirepass ${REDIS_PASSWORD}
        volumes:
            - redis_data:/data
        networks:
            - teastream-backend

    redisinsight:
        container_name: redisinsight
        image: redislabs/redisinsight:latest
        restart: no
        ports:
            - 5540:5540
        volumes:
            - redisinsight_data:/db
        networks:
            - teastream-backend

    mailhog:
        container_name: mailhog
        image: mailhog/mailhog
        restart: always
        ports:
            - '1025:1025'
            - '6030:8025'
        networks:
            - teastream-backend
    minio:
        container_name: minio
        image: minio/minio:RELEASE.2024-06-22T05-26-45Z
        restart: always
        ports:
            - '9000:9000' # API
            - '9001:9001' # Web UI
        environment:
            - MINIO_ROOT_USER=${MINIO_ROOT_USER}
            - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
        volumes:
            - minio_data:/data
        command: server --console-address ":9001" /data
        networks:
            - teastream-backend
volumes:
    postgres_data:
    redis_data:
    redisinsight_data:
    mailhog:
    minio_data:

networks:
    teastream-backend:
